### ISSUE TITLE
log_e or log_10 in calculating O3N2?

### ISSUE THREAD

**Issue by jchowk** [nyusngroup/pyMCZ#19]
https://github.com/nyusngroup/pyMCZ/blob/432b04b367e4782ac92a836ea08b2fbac3a3fd76/pyMCZ/metscales.py#L1015

Hey Fed -- Thanks for making pyMCZ available. A quick question on the implementation of one of the Maiolino+ 2008 scales. In the code, the O3N2 value is calculated as `np.log(self.O35007 / self.N26584)`. However, it looks like it should be a base-10 log: `np.log10(self.O35007 / self.N26584)`. 

Maybe I've missed something; if so, please let me know.

Best,

Chris Howk

**Comment by fedhere** [comment]
Hi Chris, I missed this till now - apologies about it. I think you are right! I will correct it. I also sent you a message: I think you implemented a few more scales. If you want to submit a pull request contributions are welcome!

**Comment by jchowk** [comment]
No worries. I missed your reply. I did implement some more scales; they may be useful to someone else. I'll have to look at how I monkeyed with other things, see if I can contribute.
